### ISSUE TITLE
Overflow Service

### ISSUE THREAD

**Issue by jasonnchann24** [jasonnchann24/hoffmen-project#10]
![image](https://user-images.githubusercontent.com/46631787/119130083-eca89f80-ba61-11eb-8a5a-e23050ff955d.png)

![image](https://user-images.githubusercontent.com/46631787/119130120-f7633480-ba61-11eb-98fd-7f21fc35a14e.png)

ini kayaknya si kotak absolute bikin bablas sama z index nya

@jrchan30

**Comment by jrchan30** [comment]
itu kok ada gapny disamping?

**Comment by jasonnchann24** [comment]
> itu kok ada gapny disamping?

@jrchan30 , iya.. bablas ke kanan di hape..
