### ISSUE TITLE
Products Section

### ISSUE THREAD

**Issue by jasonnchann24** [jasonnchann24/hoffmen-project#17]
- Jarak subtitle kejauhan
- Bentuk kotaknya yang bagian spray & diffuser, dibikin lebih persegi panjang untuk products yang dibawah & scents nya dan lebih round
- Border line kotak semua yang ada di products tebelin lg 

![image](https://user-images.githubusercontent.com/46631787/119184287-63b05900-ba9f-11eb-99cc-5bd4576a738c.png)

![image](https://user-images.githubusercontent.com/46631787/119184449-978b7e80-ba9f-11eb-8849-3041f57c1975.png)

![image](https://user-images.githubusercontent.com/46631787/119184467-9bb79c00-ba9f-11eb-9a3c-8adeb09615b0.png)

![image](https://user-images.githubusercontent.com/46631787/119184479-9f4b2300-ba9f-11eb-99c7-03db92f95a1c.png)

**Comment by jrchan30** [comment]
itu gede space subtitlenya awalny buat ngehandle klo textny panjang kayak yg di figma. Udh dikecilin lg #26
