### ISSUE TITLE
Partner Clients - Centering List

### ISSUE THREAD

**Issue by jasonnchann24** [jasonnchann24/hoffmen-project#4]
@jrchan30 
kayaknya ini list mesti lebih center?

![image](https://user-images.githubusercontent.com/46631787/116966582-bab1e200-acda-11eb-8dcc-63fd45566bd1.png)

**Comment by jrchan30** [comment]
susah itu klo dari api.. klo static udh center waktu itu

**Comment by jasonnchann24** [comment]
@jrchan30 
kan listnya tetep array? bkn html kan?

**Comment by jrchan30** [comment]
iya tapi ngebagi col ny ribet
